# Build da aplicação
FROM node:18 as build
WORKDIR /app
COPY package*.json ./
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN npm install
COPY . .
RUN npm run build

# Servir build com nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
